-- CreateEnum
CREATE TYPE "ActivityType" AS ENUM ('TASK_CREATED', 'TASK_STATUS_UPDATED', 'TASK_PRIORITY_UPDATED', 'TASK_DUE_DATE_UPDATED', 'TASK_ASSIGNED', 'TASK_UNASSIGNED', 'TASK_REASSIGNED');

-- AlterTable
ALTER TABLE "activities" ADD COLUMN     "activityType" "ActivityType" NOT NULL DEFAULT 'TASK_CREATED';
