-- CreateEnum
CREATE TYPE "ActivityType" AS ENUM ('TASK_CREATED', 'TASK_UPDATED', 'TASK_DELETED', 'TASK_ASSIGNED', 'TASK_UNASSIGNED', 'TASK_COMPLETED', 'TASK_REOPENED', 'TASK_REASSIGNED');

-- AlterTable
ALTER TABLE "activities" ADD COLUMN     "activityType" "ActivityType" NOT NULL DEFAULT 'TASK_CREATED';
